---
params:
  data_dir: "../../results/10_mofa/11_easier"
  model_dir: "../../results/10_mofa/12_mofa_analysis"
  n_cpus: "16"
---


```{r setup, include=FALSE}
library(BiocParallel)
knitr::opts_chunk$set(echo = TRUE,dpi=300,dev = "png",fig.path='figures/')
source('helper_functions.R')
DATASETS = c("Jia2018", "Sharma2019", "LUAD", "LUSC", "GTEx")
BiocParallel::register(BiocParallel::MulticoreParam(workers=as.numeric(params$n_cpus)))
```



```{r loaddata}
gtex_data = readRDS(file.path(params$data_dir, "GTEx_easier.rds"))
nsclc_data = readRDS(file.path(params$data_dir, "NSCLC_easier.rds"))
data_all = nsclc_data
for(slot in names(gtex_data)) {
  data_all[[slot]][["GTEx"]] = gtex_data[[slot]][["Lung"]]
}
```


```{r processfeatures}
feature_data = sapply(DATASETS, function(dataset_id) {
  processFeatures(data_all, dataset_id) 
}, simplify = FALSE, USE.NAMES = TRUE)

feature_data$JiaSharma = bind_rows(feature_data$Jia2018, feature_data$Sharma2019)
feature_data$NSCLC = bind_rows(feature_data$LUAD, feature_data$LUSC) %>% mutate(group = "NSCLC")
```

```{r}
for (feature in unique(feature_data$Jia2018$view)){
  generateHeatmap(feature_data$Jia2018 %>% filter(view == !!feature), feature, row_names=TRUE)
}
```


```{r runmofa, echo=FALSE, message=FALSE, results='hide'}
# Train the MOFA model
models = sapply(names(feature_data), function(dataset_id) {
  runMOFA(feature_data[[dataset_id]] %>% select(sample, feature, value, group, view),
          file.path(params$model_dir, paste0(dataset_id, ".hdf5")))
}, simplify=FALSE, USE.NAMES = TRUE)
```

```{r}
lapply(names(models), function(dataset_id) {
  print(dataset_id)
  plotResults(models[[dataset_id]], dataset_id)
})
```
### Bootstrapping analysis
```{r, message=FALSE}
# Build 100 random bootstrap datasets for each dataset 
N_BOOTSTRAP = 100
bootstrap_datasets = sapply(DATASETS, function(dataset_id) {
  samples = feature_data[[dataset_id]]$sample %>% unique()
  lapply(1:N_BOOTSTRAP, function(i) {
    set.seed(i)
    # make new sample ids unique (required for MOFA)!
    sample_df = tibble(sample = sample(samples, replace = TRUE)) %>% 
      mutate(sample_id = row_number())
    feature_data[[dataset_id]] %>% right_join(sample_df) %>%
      mutate(sample = paste0(sample, "_", sample_id))
  })
}, simplify = FALSE, USE.NAMES = TRUE)

bootstrap_datasets$JiaSharma = lapply(1:N_BOOTSTRAP, function(i) {
  bind_rows(bootstrap_datasets$Jia2018[[i]],
            bootstrap_datasets$Sharma2019[[i]])
})
bootstrap_datasets$NSCLC = lapply(1:N_BOOTSTRAP, function(i) {
  bind_rows(bootstrap_datasets$LUAD[[i]], bootstrap_datasets$LUSC[[i]])
})

```

### Run MOFA on bootstrap models

```{r}
bootstrap_models = BiocParallel::bplapply(names(bootstrap_datasets), function(dataset_id) {
  lapply(1:N_BOOTSTRAP, function(i) {
    runMOFA(
      bootstrap_datasets[[dataset_id]][[i]] %>% select(sample, feature, value, group, view) ,
      paste0(
        params$model_dir,
        paste0(dataset_id, "_boot_", stringr::str_pad(i, 3, pad = "0"), ".hdf5")
      )
    )
  })
})
names(bootstrap_models) = names(bootstrap_datasets)

save(models, bootstrap_datasets, bootstrap_models, file="./tmp_mofa.rda")
```



```{r, fig.width=15, fig.height=20}
all <- buildHeatmap(models$Jia2018, "Jia") + 
  buildHeatmap(models$Sharma2019, "Sharma") + 
  buildHeatmap(models$JiaSharma, "J+S") +
  buildHeatmap(models$LUAD, "LUAD") +
  buildHeatmap(models$LUSC, "LUSC") +
  buildHeatmap(models$NSCLC, "NSCLC") +
  buildHeatmap(models$GTEx, "GTEx")

# + buildHeatmap(features$FEAT.comb.jiasharma) + buildHeatmap(features$FEAT.luad)+buildHeatmap(features$FEAT.lusc) + buildHeatmap(features$FEAT.nsclc) + buildHeatmap(features$FEAT.crc)+buildHeatmap(features$FEAT.skcm) + buildHeatmap(features$FEAT.pbmc) + plotHMs_bootstrap(jiasharma,"J+S") + plotHMs_bootstrap(nsclc,"NSCLC") 

draw(all)

```


```{r Correlation features, echo = FALSE,  fig.width=10, fig.height=12, fig.align="center", out.width="80%", fig.cap = "Heatmap depicting the correlation of all factors of all models based on feature data. Only significant relations (p<0.001) are shown."}

# corr.feat <- getCorr(models)

 
```




